Code.require_file("../../lib/eirinchan_web/js_bundles.ex", __DIR__)

root = Path.expand("..", __DIR__)

for bundle_key <- EirinchanWeb.JsBundles.all_bundle_keys() do
  destination =
    root
    |> Path.join("static")
    |> Path.join(EirinchanWeb.JsBundles.bundle_url(bundle_key) |> String.trim_leading("/"))

  parts =
    bundle_key
    |> EirinchanWeb.JsBundles.sources_for()
    |> Enum.map(fn relative_path ->
      source_path = Path.join([root, "static", relative_path])

      unless File.exists?(source_path) do
        raise "missing JS bundle source: #{source_path}"
      end

      source =
        source_path
        |> File.read!()
        |> String.trim_trailing()

      [
        "/* Begin ",
        relative_path,
        " */\n",
        source,
        "\n/* End ",
        relative_path,
        " */\n"
      ]
      |> IO.iodata_to_binary()
    end)

  output = [
    "/* Generated by priv/scripts/build_public_bundles.exs. */\n",
    "/* Bundle: ",
    Atom.to_string(bundle_key),
    " */\n\n",
    Enum.join(parts, "\n")
  ]

  File.write!(destination, output)
end
